<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Operations;


class GetOpenApiSpecResponse
{
	
    public string $contentType;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Returns the openapi specification file
     * 
     * @var ?string $getOpenApiSpec200TextPlainBinaryString
     */
	
    public ?string $getOpenApiSpec200TextPlainBinaryString = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getOpenApiSpec200TextPlainBinaryString = null;
	}
}
