<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Operations;


class ListSourceDefinitionsResponse
{
	
    public string $contentType;
    
    /**
     * Successful operation
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\SourceDefinitionReadList $sourceDefinitionReadList
     */
	
    public ?\airbyte\airbyte_oss\Models\Shared\SourceDefinitionReadList $sourceDefinitionReadList = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->sourceDefinitionReadList = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
