<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Operations;


class SetInstancewideDestinationOauthParamsResponse
{
	
    public string $contentType;
    
    /**
     * Exception occurred; see message for details.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\KnownExceptionInfo $knownExceptionInfo
     */
	
    public ?\airbyte\airbyte_oss\Models\Shared\KnownExceptionInfo $knownExceptionInfo = null;
    
    /**
     * Object with given id was not found.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\NotFoundKnownExceptionInfo $notFoundKnownExceptionInfo
     */
	
    public ?\airbyte\airbyte_oss\Models\Shared\NotFoundKnownExceptionInfo $notFoundKnownExceptionInfo = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->knownExceptionInfo = null;
		$this->notFoundKnownExceptionInfo = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
