<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class ActorCatalogWithUpdatedAtCatalog
{
	public function __construct()
	{
	}
}
