<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * ActorDefinitionResourceRequirements - actor definition specific resource requirements. if default is set, these are the requirements that should be set for ALL jobs run for this actor definition. it is overriden by the job type specific configurations. if not set, the platform will use defaults. these values will be overriden by configuration at the connection level.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class ActorDefinitionResourceRequirements
{
    /**
     * optional resource requirements to run workers (blank for unbounded allocations)
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\ResourceRequirements $default
     */
	#[\JMS\Serializer\Annotation\SerializedName('default')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ResourceRequirements')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ResourceRequirements $default = null;
    
    /**
     * $jobSpecific
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\JobTypeResourceLimit> $jobSpecific
     */
	#[\JMS\Serializer\Annotation\SerializedName('jobSpecific')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\JobTypeResourceLimit>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $jobSpecific = null;
    
	public function __construct()
	{
		$this->default = null;
		$this->jobSpecific = null;
	}
}
