<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class AdvancedAuth
{
	#[\JMS\Serializer\Annotation\SerializedName('authFlowType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\AdvancedAuthAuthFlowTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AdvancedAuthAuthFlowTypeEnum $authFlowType = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauthConfigSpecification')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OAuthConfigSpecification')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OAuthConfigSpecification $oauthConfigSpecification = null;
    
    /**
     * Json Path to a field in the connectorSpecification that should exist for the advanced auth to be applicable.
     * 
     * @var ?array<string> $predicateKey
     */
	#[\JMS\Serializer\Annotation\SerializedName('predicateKey')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $predicateKey = null;
    
    /**
     * Value of the predicate_key fields for the advanced auth to be applicable.
     * 
     * @var ?string $predicateValue
     */
	#[\JMS\Serializer\Annotation\SerializedName('predicateValue')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $predicateValue = null;
    
	public function __construct()
	{
		$this->authFlowType = null;
		$this->oauthConfigSpecification = null;
		$this->predicateKey = null;
		$this->predicateValue = null;
	}
}
