<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * AirbyteStreamAndConfiguration - each stream is split in two parts; the immutable schema from source and mutable configuration for destination
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class AirbyteStreamAndConfiguration
{
    /**
     * the mutable part of the stream to configure the destination
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\AirbyteStreamConfiguration $config
     */
	#[\JMS\Serializer\Annotation\SerializedName('config')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AirbyteStreamConfiguration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AirbyteStreamConfiguration $config = null;
    
    /**
     * the immutable schema defined by the source
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\AirbyteStream $stream
     */
	#[\JMS\Serializer\Annotation\SerializedName('stream')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AirbyteStream')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AirbyteStream $stream = null;
    
	public function __construct()
	{
		$this->config = null;
		$this->stream = null;
	}
}
