<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * AirbyteCatalog - describes the available schema (catalog).
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class AirbyteCatalog
{
    /**
     * $streams
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\AirbyteStreamAndConfiguration> $streams
     */
	#[\JMS\Serializer\Annotation\SerializedName('streams')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\AirbyteStreamAndConfiguration>')]
    public array $streams;
    
	public function __construct()
	{
		$this->streams = [];
	}
}
