<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * AirbyteStream - the immutable schema defined by the source
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class AirbyteStream
{
    /**
     * Path to the field that will be used to determine if a record is new or modified since the last sync. If not provided by the source, the end user will have to specify the comparable themselves.
     * 
     * @var ?array<string> $defaultCursorField
     */
	#[\JMS\Serializer\Annotation\SerializedName('defaultCursorField')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $defaultCursorField = null;
    
    /**
     * Stream schema using Json Schema specs.
     * 
     * @var ?array<string, mixed> $jsonSchema
     */
	#[\JMS\Serializer\Annotation\SerializedName('jsonSchema')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $jsonSchema = null;
    
    /**
     * Stream's name.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Optional Source-defined namespace. Airbyte streams from the same sources should have the same namespace. Currently only used by JDBC destinations to determine what schema to write to.
     * 
     * @var ?string $namespace
     */
	#[\JMS\Serializer\Annotation\SerializedName('namespace')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $namespace = null;
    
    /**
     * If the source defines the cursor field, then any other cursor field inputs will be ignored. If it does not, either the user_provided one is used, or the default one is used as a backup.
     * 
     * @var ?bool $sourceDefinedCursor
     */
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinedCursor')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $sourceDefinedCursor = null;
    
    /**
     * If the source defines the primary key, paths to the fields that will be used as a primary key. If not provided by the source, the end user will have to specify the primary key themselves.
     * 
     * @var ?array<array<string>> $sourceDefinedPrimaryKey
     */
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinedPrimaryKey')]
    #[\JMS\Serializer\Annotation\Type('array<array<string>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $sourceDefinedPrimaryKey = null;
    
    /**
     * $supportedSyncModes
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\SyncMode> $supportedSyncModes
     */
	#[\JMS\Serializer\Annotation\SerializedName('supportedSyncModes')]
    #[\JMS\Serializer\Annotation\Type('array<enum<airbyte\airbyte_oss\Models\Shared\SyncMode>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $supportedSyncModes = null;
    
	public function __construct()
	{
		$this->defaultCursorField = null;
		$this->jsonSchema = null;
		$this->name = "";
		$this->namespace = null;
		$this->sourceDefinedCursor = null;
		$this->sourceDefinedPrimaryKey = null;
		$this->supportedSyncModes = null;
	}
}
