<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * AirbyteStreamConfiguration - the mutable part of the stream to configure the destination
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class AirbyteStreamConfiguration
{
    /**
     * Alias name to the stream to be used in the destination
     * 
     * @var ?string $aliasName
     */
	#[\JMS\Serializer\Annotation\SerializedName('aliasName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $aliasName = null;
    
    /**
     * Path to the field that will be used to determine if a record is new or modified since the last sync. This field is REQUIRED if `sync_mode` is `incremental`. Otherwise it is ignored.
     * 
     * @var ?array<string> $cursorField
     */
	#[\JMS\Serializer\Annotation\SerializedName('cursorField')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $cursorField = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationSyncMode')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\DestinationSyncMode>')]
    public DestinationSyncMode $destinationSyncMode;
    
    /**
     * Whether field selection should be enabled. If this is true, only the properties in `selectedFields` will be included.
     * 
     * @var ?bool $fieldSelectionEnabled
     */
	#[\JMS\Serializer\Annotation\SerializedName('fieldSelectionEnabled')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $fieldSelectionEnabled = null;
    
    /**
     * Paths to the fields that will be used as primary key. This field is REQUIRED if `destination_sync_mode` is `*_dedup`. Otherwise it is ignored.
     * 
     * @var ?array<array<string>> $primaryKey
     */
	#[\JMS\Serializer\Annotation\SerializedName('primaryKey')]
    #[\JMS\Serializer\Annotation\Type('array<array<string>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $primaryKey = null;
    
    /**
     * If this is true, the stream is selected with all of its properties. For new connections, this considers if the stream is suggested or not
     * 
     * @var ?bool $selected
     */
	#[\JMS\Serializer\Annotation\SerializedName('selected')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $selected = null;
    
    /**
     * Paths to the fields that will be included in the configured catalog. This must be set if `fieldSelectedEnabled` is set. An empty list indicates that no properties will be included.
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\SelectedFieldInfo> $selectedFields
     */
	#[\JMS\Serializer\Annotation\SerializedName('selectedFields')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\SelectedFieldInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $selectedFields = null;
    
    /**
     * Does the connector suggest that this stream be enabled by default?
     * 
     * @var ?bool $suggested
     */
	#[\JMS\Serializer\Annotation\SerializedName('suggested')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $suggested = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('syncMode')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\SyncMode>')]
    public SyncMode $syncMode;
    
	public function __construct()
	{
		$this->aliasName = null;
		$this->cursorField = null;
		$this->destinationSyncMode = \airbyte\airbyte_oss\Models\Shared\DestinationSyncMode::APPEND;
		$this->fieldSelectionEnabled = null;
		$this->primaryKey = null;
		$this->selected = null;
		$this->selectedFields = null;
		$this->suggested = null;
		$this->syncMode = \airbyte\airbyte_oss\Models\Shared\SyncMode::FULL_REFRESH;
	}
}
