<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/** Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known. */
enum AttemptFailureTypeEnum: string
{
    case CONFIG_ERROR = 'config_error';
    case SYSTEM_ERROR = 'system_error';
    case MANUAL_CANCELLATION = 'manual_cancellation';
    case REFRESH_SCHEMA = 'refresh_schema';
}
