<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/** Indicates where the error originated. If not set, the origin of error is not well known. */
enum AttemptFailureOriginEnum: string
{
    case SOURCE = 'source';
    case DESTINATION = 'destination';
    case REPLICATION = 'replication';
    case PERSISTENCE = 'persistence';
    case NORMALIZATION = 'normalization';
    case DBT = 'dbt';
    case AIRBYTE_PLATFORM = 'airbyte_platform';
    case UNKNOWN = 'unknown';
}
