<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class AttemptNormalizationStatusRead
{
	#[\JMS\Serializer\Annotation\SerializedName('attemptNumber')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $attemptNumber = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('hasNormalizationFailed')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasNormalizationFailed = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('hasRecordsCommitted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $hasRecordsCommitted = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('recordsCommitted')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $recordsCommitted = null;
    
	public function __construct()
	{
		$this->attemptNumber = null;
		$this->hasNormalizationFailed = null;
		$this->hasRecordsCommitted = null;
		$this->recordsCommitted = null;
	}
}
