<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class AttemptStreamStats
{
	#[\JMS\Serializer\Annotation\SerializedName('stats')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AttemptStats')]
    public AttemptStats $stats;
    
	#[\JMS\Serializer\Annotation\SerializedName('streamName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $streamName;
    
	#[\JMS\Serializer\Annotation\SerializedName('streamNamespace')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $streamNamespace = null;
    
	public function __construct()
	{
		$this->stats = new \airbyte\airbyte_oss\Models\Shared\AttemptStats();
		$this->streamName = "";
		$this->streamNamespace = null;
	}
}
