<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class AttemptFailureReason
{
	#[\JMS\Serializer\Annotation\SerializedName('externalMessage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $externalMessage = null;
    
    /**
     * Indicates where the error originated. If not set, the origin of error is not well known.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\AttemptFailureOriginEnum $failureOrigin
     */
	#[\JMS\Serializer\Annotation\SerializedName('failureOrigin')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\AttemptFailureOriginEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AttemptFailureOriginEnum $failureOrigin = null;
    
    /**
     * Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\AttemptFailureTypeEnum $failureType
     */
	#[\JMS\Serializer\Annotation\SerializedName('failureType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\AttemptFailureTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AttemptFailureTypeEnum $failureType = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('internalMessage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $internalMessage = null;
    
    /**
     * True if it is known that retrying may succeed, e.g. for a transient failure. False if it is known that a retry will not succeed, e.g. for a configuration issue. If not set, retryable status is not well known.
     * 
     * @var ?bool $retryable
     */
	#[\JMS\Serializer\Annotation\SerializedName('retryable')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $retryable = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('stacktrace')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $stacktrace = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('timestamp')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $timestamp;
    
	public function __construct()
	{
		$this->externalMessage = null;
		$this->failureOrigin = null;
		$this->failureType = null;
		$this->internalMessage = null;
		$this->retryable = null;
		$this->stacktrace = null;
		$this->timestamp = 0;
	}
}
