<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class AttemptFailureSummary
{
    /**
     * $failures
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\AttemptFailureReason> $failures
     */
	#[\JMS\Serializer\Annotation\SerializedName('failures')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\AttemptFailureReason>')]
    public array $failures;
    
    /**
     * True if the number of committed records for this attempt was greater than 0. False if 0 records were committed. If not set, the number of committed records is unknown.
     * 
     * @var ?bool $partialSuccess
     */
	#[\JMS\Serializer\Annotation\SerializedName('partialSuccess')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $partialSuccess = null;
    
	public function __construct()
	{
		$this->failures = [];
		$this->partialSuccess = null;
	}
}
