<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * CheckConnectionRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class CheckConnectionRead
{
	#[\JMS\Serializer\Annotation\SerializedName('jobInfo')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SynchronousJobRead')]
    public SynchronousJobRead $jobInfo;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $message = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\CheckConnectionReadStatus>')]
    public CheckConnectionReadStatus $status;
    
	public function __construct()
	{
		$this->jobInfo = new \airbyte\airbyte_oss\Models\Shared\SynchronousJobRead();
		$this->message = null;
		$this->status = \airbyte\airbyte_oss\Models\Shared\CheckConnectionReadStatus::Succeeded;
	}
}
