<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class CompleteDestinationOAuthRequest
{
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $destinationId = null;
    
    /**
     * The values required to configure OAuth flows. The schema for this must match the `OAuthConfigSpecification.oauthUserInputFromConnectorConfigSpecification` schema.
     * 
     * @var mixed $oAuthInputConfiguration
     */
	#[\JMS\Serializer\Annotation\SerializedName('oAuthInputConfiguration')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $oAuthInputConfiguration = null;
    
    /**
     * The query parameters present in the redirect URL after a user granted consent e.g auth code
     * 
     * @var ?array<string, mixed> $queryParams
     */
	#[\JMS\Serializer\Annotation\SerializedName('queryParams')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $queryParams = null;
    
    /**
     * When completing OAuth flow to gain an access token, some API sometimes requires to verify that the app re-send the redirectUrl that was used when consent was given.
     * 
     * @var ?string $redirectUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('redirectUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $redirectUrl = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->destinationDefinitionId = "";
		$this->destinationId = null;
		$this->oAuthInputConfiguration = null;
		$this->queryParams = null;
		$this->redirectUrl = null;
		$this->workspaceId = "";
	}
}
