<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * ConnectionScheduleData - schedule for when the the connection should run, per the schedule type
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class ConnectionScheduleData
{
	#[\JMS\Serializer\Annotation\SerializedName('basicSchedule')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ConnectionScheduleDataBasicSchedule')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ConnectionScheduleDataBasicSchedule $basicSchedule = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('cron')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ConnectionScheduleDataCron')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ConnectionScheduleDataCron $cron = null;
    
	public function __construct()
	{
		$this->basicSchedule = null;
		$this->cron = null;
	}
}
