<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class ConnectionScheduleDataCron
{
	#[\JMS\Serializer\Annotation\SerializedName('cronExpression')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cronExpression;
    
	#[\JMS\Serializer\Annotation\SerializedName('cronTimeZone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $cronTimeZone;
    
	public function __construct()
	{
		$this->cronExpression = "";
		$this->cronTimeZone = "";
	}
}
