<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/** Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced. */
enum ConnectionStatus: string
{
    case ACTIVE = 'active';
    case INACTIVE = 'inactive';
    case DEPRECATED = 'deprecated';
}
