<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class ConnectionStateCreateOrUpdate
{
	#[\JMS\Serializer\Annotation\SerializedName('connectionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $connectionId;
    
    /**
     * Contains the state for a connection. The stateType field identifies what type of state it is. Only the field corresponding to that type will be set, the rest will be null. If stateType=not_set, then none of the fields will be set.
     * 
     * @var \airbyte\airbyte_oss\Models\Shared\ConnectionState $connectionState
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionState')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ConnectionState')]
    public ConnectionState $connectionState;
    
	public function __construct()
	{
		$this->connectionId = "";
		$this->connectionState = new \airbyte\airbyte_oss\Models\Shared\ConnectionState();
	}
}
