<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class CustomSourceDefinitionCreate
{
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinition')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SourceDefinitionCreate')]
    public SourceDefinitionCreate $sourceDefinition;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->sourceDefinition = new \airbyte\airbyte_oss\Models\Shared\SourceDefinitionCreate();
		$this->workspaceId = "";
	}
}
