<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * DestinationRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class DestinationRead
{
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     * 
     * @var mixed $connectionConfiguration
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionConfiguration')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $connectionConfiguration;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationId;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationName;
    
	#[\JMS\Serializer\Annotation\SerializedName('icon')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $icon = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->connectionConfiguration = null;
		$this->destinationDefinitionId = "";
		$this->destinationId = "";
		$this->destinationName = "";
		$this->icon = null;
		$this->name = "";
		$this->workspaceId = "";
	}
}
