<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class DestinationCreate
{
    /**
     * The values required to configure the destination. The schema for this must match the schema return by destination_definition_specifications/get for the destinationDefinition.
     * 
     * @var mixed $connectionConfiguration
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionConfiguration')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $connectionConfiguration;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->connectionConfiguration = null;
		$this->destinationDefinitionId = "";
		$this->name = "";
		$this->workspaceId = "";
	}
}
