<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * DestinationDefinitionSpecificationRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class DestinationDefinitionSpecificationRead
{
	#[\JMS\Serializer\Annotation\SerializedName('advancedAuth')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AdvancedAuth')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AdvancedAuth $advancedAuth = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('authSpecification')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\DestinationAuthSpecification')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DestinationAuthSpecification $authSpecification = null;
    
    /**
     * The specification for what values are required to configure the destinationDefinition.
     * 
     * @var mixed $connectionSpecification
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionSpecification')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public mixed $connectionSpecification = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('documentationUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $documentationUrl = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('jobInfo')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SynchronousJobRead')]
    public SynchronousJobRead $jobInfo;
    
    /**
     * $supportedDestinationSyncModes
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\DestinationSyncMode> $supportedDestinationSyncModes
     */
	#[\JMS\Serializer\Annotation\SerializedName('supportedDestinationSyncModes')]
    #[\JMS\Serializer\Annotation\Type('array<enum<airbyte\airbyte_oss\Models\Shared\DestinationSyncMode>>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $supportedDestinationSyncModes = null;
    
	public function __construct()
	{
		$this->advancedAuth = null;
		$this->authSpecification = null;
		$this->connectionSpecification = null;
		$this->destinationDefinitionId = "";
		$this->documentationUrl = null;
		$this->jobInfo = new \airbyte\airbyte_oss\Models\Shared\SynchronousJobRead();
		$this->supportedDestinationSyncModes = null;
	}
}
