<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * DestinationDefinitionReadList - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class DestinationDefinitionReadList
{
    /**
     * $destinationDefinitions
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\DestinationDefinitionRead> $destinationDefinitions
     */
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitions')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\DestinationDefinitionRead>')]
    public array $destinationDefinitions;
    
	public function __construct()
	{
		$this->destinationDefinitions = [];
	}
}
