<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum DestinationSyncModeEnum: string
{
    case APPEND = 'append';
    case OVERWRITE = 'overwrite';
    case APPEND_DEDUP = 'append_dedup';
}
