<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class DestinationDefinitionIdRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
	public function __construct()
	{
		$this->destinationDefinitionId = "";
	}
}
