<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * DiscoverCatalogResult - Successful Operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class DiscoverCatalogResult
{
	#[\JMS\Serializer\Annotation\SerializedName('catalogId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $catalogId;
    
	public function __construct()
	{
		$this->catalogId = "";
	}
}
