<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class FieldSchemaUpdate
{
    /**
     * JSONSchema representation of the field
     * 
     * @var \airbyte\airbyte_oss\Models\Shared\FieldSchema $newSchema
     */
	#[\JMS\Serializer\Annotation\SerializedName('newSchema')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\FieldSchema')]
    public FieldSchema $newSchema;
    
    /**
     * JSONSchema representation of the field
     * 
     * @var \airbyte\airbyte_oss\Models\Shared\FieldSchema $oldSchema
     */
	#[\JMS\Serializer\Annotation\SerializedName('oldSchema')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\FieldSchema')]
    public FieldSchema $oldSchema;
    
	public function __construct()
	{
		$this->newSchema = new \airbyte\airbyte_oss\Models\Shared\FieldSchema();
		$this->oldSchema = new \airbyte\airbyte_oss\Models\Shared\FieldSchema();
	}
}
