<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum FieldTransformTransformTypeEnum: string
{
    case ADD_FIELD = 'add_field';
    case REMOVE_FIELD = 'remove_field';
    case UPDATE_FIELD_SCHEMA = 'update_field_schema';
}
