<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum FieldTransformTransformType: string
{
    case AddField = 'add_field';
    case RemoveField = 'remove_field';
    case UpdateFieldSchema = 'update_field_schema';
}
