<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class GlobalState
{
	#[\JMS\Serializer\Annotation\SerializedName('shared_state')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\StateBlob')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StateBlob $sharedState = null;
    
    /**
     * $streamStates
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\StreamState> $streamStates
     */
	#[\JMS\Serializer\Annotation\SerializedName('streamStates')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\StreamState>')]
    public array $streamStates;
    
	public function __construct()
	{
		$this->sharedState = null;
		$this->streamStates = [];
	}
}
