<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * InternalOperationResult - Successful Operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class InternalOperationResult
{
	#[\JMS\Serializer\Annotation\SerializedName('succeeded')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $succeeded;
    
	public function __construct()
	{
		$this->succeeded = false;
	}
}
