<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * InvalidInputExceptionInfo - Input failed validation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class InvalidInputExceptionInfo
{
	#[\JMS\Serializer\Annotation\SerializedName('exceptionClassName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $exceptionClassName = null;
    
    /**
     * $exceptionStack
     * 
     * @var ?array<string> $exceptionStack
     */
	#[\JMS\Serializer\Annotation\SerializedName('exceptionStack')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $exceptionStack = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
    /**
     * $validationErrors
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\InvalidInputProperty> $validationErrors
     */
	#[\JMS\Serializer\Annotation\SerializedName('validationErrors')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\InvalidInputProperty>')]
    public array $validationErrors;
    
	public function __construct()
	{
		$this->exceptionClassName = null;
		$this->exceptionStack = null;
		$this->message = "";
		$this->validationErrors = [];
	}
}
