<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum JobConfigTypeEnum: string
{
    case CHECK_CONNECTION_SOURCE = 'check_connection_source';
    case CHECK_CONNECTION_DESTINATION = 'check_connection_destination';
    case DISCOVER_SCHEMA = 'discover_schema';
    case GET_SPEC = 'get_spec';
    case SYNC = 'sync';
    case RESET_CONNECTION = 'reset_connection';
}
