<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class JobDebugRead
{
	#[\JMS\Serializer\Annotation\SerializedName('airbyteVersion')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $airbyteVersion;
    
	#[\JMS\Serializer\Annotation\SerializedName('configId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $configId;
    
	#[\JMS\Serializer\Annotation\SerializedName('configType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobConfigType>')]
    public JobConfigType $configType;
    
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinition')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\DestinationDefinitionRead')]
    public DestinationDefinitionRead $destinationDefinition;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinition')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SourceDefinitionRead')]
    public SourceDefinitionRead $sourceDefinition;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobStatus>')]
    public JobStatus $status;
    
	public function __construct()
	{
		$this->airbyteVersion = "";
		$this->configId = "";
		$this->configType = \airbyte\airbyte_oss\Models\Shared\JobConfigType::CHECK_CONNECTION_SOURCE;
		$this->destinationDefinition = new \airbyte\airbyte_oss\Models\Shared\DestinationDefinitionRead();
		$this->id = 0;
		$this->sourceDefinition = new \airbyte\airbyte_oss\Models\Shared\SourceDefinitionRead();
		$this->status = \airbyte\airbyte_oss\Models\Shared\JobStatus::PENDING;
	}
}
