<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * JobInfoRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class JobInfoRead
{
    /**
     * $attempts
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\AttemptInfoRead> $attempts
     */
	#[\JMS\Serializer\Annotation\SerializedName('attempts')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\AttemptInfoRead>')]
    public array $attempts;
    
	#[\JMS\Serializer\Annotation\SerializedName('job')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\JobRead')]
    public JobRead $job;
    
	public function __construct()
	{
		$this->attempts = [];
		$this->job = new \airbyte\airbyte_oss\Models\Shared\JobRead();
	}
}
