<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * JobInfoLightRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class JobInfoLightRead
{
	#[\JMS\Serializer\Annotation\SerializedName('job')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\JobRead')]
    public JobRead $job;
    
	public function __construct()
	{
		$this->job = new \airbyte\airbyte_oss\Models\Shared\JobRead();
	}
}
