<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class JobListRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('configId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $configId;
    
    /**
     * $configTypes
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\JobConfigTypeEnum> $configTypes
     */
	#[\JMS\Serializer\Annotation\SerializedName('configTypes')]
    #[\JMS\Serializer\Annotation\Type('array<enum<airbyte\airbyte_oss\Models\Shared\JobConfigTypeEnum>>')]
    public array $configTypes;
    
	#[\JMS\Serializer\Annotation\SerializedName('includingJobId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $includingJobId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('pagination')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\Pagination')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Pagination $pagination = null;
    
	public function __construct()
	{
		$this->configId = "";
		$this->configTypes = [];
		$this->includingJobId = null;
		$this->pagination = null;
	}
}
