<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class JobRead
{
	#[\JMS\Serializer\Annotation\SerializedName('configId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $configId;
    
	#[\JMS\Serializer\Annotation\SerializedName('configType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobConfigType>')]
    public JobConfigType $configType;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
    /**
     * contains information about how a reset was configured. only populated if the job was a reset.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\ResetConfig $resetConfig
     */
	#[\JMS\Serializer\Annotation\SerializedName('resetConfig')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ResetConfig')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ResetConfig $resetConfig = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('startedAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $startedAt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobStatus>')]
    public JobStatus $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $updatedAt;
    
	public function __construct()
	{
		$this->configId = "";
		$this->configType = \airbyte\airbyte_oss\Models\Shared\JobConfigType::CheckConnectionSource;
		$this->createdAt = 0;
		$this->id = 0;
		$this->resetConfig = null;
		$this->startedAt = null;
		$this->status = \airbyte\airbyte_oss\Models\Shared\JobStatus::Pending;
		$this->updatedAt = 0;
	}
}
