<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum JobStatus: string
{
    case PENDING = 'pending';
    case RUNNING = 'running';
    case INCOMPLETE = 'incomplete';
    case FAILED = 'failed';
    case SUCCEEDED = 'succeeded';
    case CANCELLED = 'cancelled';
}
