<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum JobStatus: string
{
    case Pending = 'pending';
    case Running = 'running';
    case Incomplete = 'incomplete';
    case Failed = 'failed';
    case Succeeded = 'succeeded';
    case Cancelled = 'cancelled';
}
