<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/** enum that describes the different types of jobs that the platform runs. */
enum JobType: string
{
    case GetSpec = 'get_spec';
    case CheckConnection = 'check_connection';
    case DiscoverSchema = 'discover_schema';
    case Sync = 'sync';
    case ResetConnection = 'reset_connection';
    case ConnectionUpdater = 'connection_updater';
    case Replicate = 'replicate';
}
