<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/** enum that describes the different types of jobs that the platform runs. */
enum JobType: string
{
    case GET_SPEC = 'get_spec';
    case CHECK_CONNECTION = 'check_connection';
    case DISCOVER_SCHEMA = 'discover_schema';
    case SYNC = 'sync';
    case RESET_CONNECTION = 'reset_connection';
    case CONNECTION_UPDATER = 'connection_updater';
    case REPLICATE = 'replicate';
}
