<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class JobWithAttemptsRead
{
    /**
     * $attempts
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\AttemptRead> $attempts
     */
	#[\JMS\Serializer\Annotation\SerializedName('attempts')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\AttemptRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $attempts = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('job')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\JobRead')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?JobRead $job = null;
    
	public function __construct()
	{
		$this->attempts = null;
		$this->job = null;
	}
}
