<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class LogRead
{
    /**
     * $logLines
     * 
     * @var array<string> $logLines
     */
	#[\JMS\Serializer\Annotation\SerializedName('logLines')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $logLines;
    
	public function __construct()
	{
		$this->logLines = [];
	}
}
