<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * NormalizationDestinationDefinitionConfig - describes a normalization config for destination definition
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class NormalizationDestinationDefinitionConfig
{
    /**
     * a field indicating the type of integration dialect to use for normalization.
     * 
     * @var ?string $normalizationIntegrationType
     */
	#[\JMS\Serializer\Annotation\SerializedName('normalizationIntegrationType')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $normalizationIntegrationType = null;
    
    /**
     * a field indicating the name of the repository to be used for normalization. If the value of the flag is NULL - normalization is not used.
     * 
     * @var ?string $normalizationRepository
     */
	#[\JMS\Serializer\Annotation\SerializedName('normalizationRepository')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $normalizationRepository = null;
    
    /**
     * a field indicating the tag of the docker repository to be used for normalization.
     * 
     * @var ?string $normalizationTag
     */
	#[\JMS\Serializer\Annotation\SerializedName('normalizationTag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $normalizationTag = null;
    
    /**
     * whether the destination definition supports normalization.
     * 
     * @var bool $supported
     */
	#[\JMS\Serializer\Annotation\SerializedName('supported')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $supported;
    
	public function __construct()
	{
		$this->normalizationIntegrationType = null;
		$this->normalizationRepository = null;
		$this->normalizationTag = null;
		$this->supported = false;
	}
}
