<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * NotFoundKnownExceptionInfo - Object with given id was not found.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class NotFoundKnownExceptionInfo
{
	#[\JMS\Serializer\Annotation\SerializedName('exceptionClassName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $exceptionClassName = null;
    
    /**
     * $exceptionStack
     * 
     * @var ?array<string> $exceptionStack
     */
	#[\JMS\Serializer\Annotation\SerializedName('exceptionStack')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $exceptionStack = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	#[\JMS\Serializer\Annotation\SerializedName('rootCauseExceptionClassName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $rootCauseExceptionClassName = null;
    
    /**
     * $rootCauseExceptionStack
     * 
     * @var ?array<string> $rootCauseExceptionStack
     */
	#[\JMS\Serializer\Annotation\SerializedName('rootCauseExceptionStack')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $rootCauseExceptionStack = null;
    
	public function __construct()
	{
		$this->exceptionClassName = null;
		$this->exceptionStack = null;
		$this->id = null;
		$this->message = "";
		$this->rootCauseExceptionClassName = null;
		$this->rootCauseExceptionStack = null;
	}
}
