<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class Notification
{
	#[\JMS\Serializer\Annotation\SerializedName('customerioConfiguration')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\CustomerioNotificationConfiguration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CustomerioNotificationConfiguration $customerioConfiguration = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('notificationType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\NotificationType>')]
    public NotificationType $notificationType;
    
	#[\JMS\Serializer\Annotation\SerializedName('sendOnFailure')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $sendOnFailure;
    
	#[\JMS\Serializer\Annotation\SerializedName('sendOnSuccess')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $sendOnSuccess;
    
	#[\JMS\Serializer\Annotation\SerializedName('slackConfiguration')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SlackNotificationConfiguration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SlackNotificationConfiguration $slackConfiguration = null;
    
	public function __construct()
	{
		$this->customerioConfiguration = null;
		$this->notificationType = \airbyte\airbyte_oss\Models\Shared\NotificationType::Slack;
		$this->sendOnFailure = false;
		$this->sendOnSuccess = false;
		$this->slackConfiguration = null;
	}
}
