<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class OperatorDbt
{
	#[\JMS\Serializer\Annotation\SerializedName('dbtArguments')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dbtArguments = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('dockerImage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $dockerImage = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('gitRepoBranch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $gitRepoBranch = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('gitRepoUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $gitRepoUrl;
    
	public function __construct()
	{
		$this->dbtArguments = null;
		$this->dockerImage = null;
		$this->gitRepoBranch = null;
		$this->gitRepoUrl = "";
	}
}
