<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class OperatorNormalization
{
	#[\JMS\Serializer\Annotation\SerializedName('option')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\OperatorNormalizationOptionEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorNormalizationOptionEnum $option = null;
    
	public function __construct()
	{
		$this->option = null;
	}
}
