<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class OperationUpdate
{
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('operationId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $operationId;
    
	#[\JMS\Serializer\Annotation\SerializedName('operatorConfiguration')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OperatorConfiguration')]
    public OperatorConfiguration $operatorConfiguration;
    
	public function __construct()
	{
		$this->name = "";
		$this->operationId = "";
		$this->operatorConfiguration = new \airbyte\airbyte_oss\Models\Shared\OperatorConfiguration();
	}
}
