<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class OperatorConfiguration
{
	#[\JMS\Serializer\Annotation\SerializedName('dbt')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OperatorDbt')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorDbt $dbt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('normalization')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OperatorNormalization')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorNormalization $normalization = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('operatorType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\OperatorTypeEnum>')]
    public OperatorTypeEnum $operatorType;
    
	#[\JMS\Serializer\Annotation\SerializedName('webhook')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OperatorWebhook')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorWebhook $webhook = null;
    
	public function __construct()
	{
		$this->dbt = null;
		$this->normalization = null;
		$this->operatorType = \airbyte\airbyte_oss\Models\Shared\OperatorTypeEnum::NORMALIZATION;
		$this->webhook = null;
	}
}
