<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum OperatorType: string
{
    case NORMALIZATION = 'normalization';
    case DBT = 'dbt';
    case WEBHOOK = 'webhook';
}
