<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class OperatorWebhook
{
	#[\JMS\Serializer\Annotation\SerializedName('dbtCloud')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\OperatorWebhookDbtCloud')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorWebhookDbtCloud $dbtCloud = null;
    
    /**
     * DEPRECATED. Populate dbtCloud instead.
     * 
     * @var ?string $executionBody
     */
	#[\JMS\Serializer\Annotation\SerializedName('executionBody')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $executionBody = null;
    
    /**
     * DEPRECATED. Populate dbtCloud instead.
     * 
     * @var ?string $executionUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('executionUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $executionUrl = null;
    
    /**
     * The id of the webhook configs to use from the workspace.
     * 
     * @var ?string $webhookConfigId
     */
	#[\JMS\Serializer\Annotation\SerializedName('webhookConfigId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $webhookConfigId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('webhookType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\OperatorWebhookWebhookTypeEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OperatorWebhookWebhookTypeEnum $webhookType = null;
    
	public function __construct()
	{
		$this->dbtCloud = null;
		$this->executionBody = null;
		$this->executionUrl = null;
		$this->webhookConfigId = null;
		$this->webhookType = null;
	}
}
