<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * PrivateSourceDefinitionReadList - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class PrivateSourceDefinitionReadList
{
    /**
     * $sourceDefinitions
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\PrivateSourceDefinitionRead> $sourceDefinitions
     */
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinitions')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\PrivateSourceDefinitionRead>')]
    public array $sourceDefinitions;
    
	public function __construct()
	{
		$this->sourceDefinitions = [];
	}
}
