<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * PrivateSourceDefinitionRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class PrivateSourceDefinitionRead
{
	#[\JMS\Serializer\Annotation\SerializedName('granted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $granted;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinition')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SourceDefinitionRead')]
    public SourceDefinitionRead $sourceDefinition;
    
	public function __construct()
	{
		$this->granted = false;
		$this->sourceDefinition = new \airbyte\airbyte_oss\Models\Shared\SourceDefinitionRead();
	}
}
