<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum ReleaseStageEnum: string
{
    case ALPHA = 'alpha';
    case BETA = 'beta';
    case GENERALLY_AVAILABLE = 'generally_available';
    case CUSTOM = 'custom';
}
