<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum ReleaseStage: string
{
    case Alpha = 'alpha';
    case Beta = 'beta';
    case GenerallyAvailable = 'generally_available';
    case Custom = 'custom';
}
