<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * ResetConfig - contains information about how a reset was configured. only populated if the job was a reset.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class ResetConfig
{
    /**
     * $streamsToReset
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\StreamDescriptor> $streamsToReset
     */
	#[\JMS\Serializer\Annotation\SerializedName('streamsToReset')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\StreamDescriptor>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $streamsToReset = null;
    
	public function __construct()
	{
		$this->streamsToReset = null;
	}
}
