<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SaveStatsRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('attemptNumber')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $attemptNumber;
    
	#[\JMS\Serializer\Annotation\SerializedName('jobId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $jobId;
    
	#[\JMS\Serializer\Annotation\SerializedName('stats')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AttemptStats')]
    public AttemptStats $stats;
    
    /**
     * $streamStats
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\AttemptStreamStats> $streamStats
     */
	#[\JMS\Serializer\Annotation\SerializedName('streamStats')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\AttemptStreamStats>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $streamStats = null;
    
	public function __construct()
	{
		$this->attemptNumber = 0;
		$this->jobId = 0;
		$this->stats = new \airbyte\airbyte_oss\Models\Shared\AttemptStats();
		$this->streamStats = null;
	}
}
