<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SaveAttemptSyncConfigRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('attemptNumber')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $attemptNumber;
    
	#[\JMS\Serializer\Annotation\SerializedName('jobId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $jobId;
    
	#[\JMS\Serializer\Annotation\SerializedName('syncConfig')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AttemptSyncConfig')]
    public AttemptSyncConfig $syncConfig;
    
	public function __construct()
	{
		$this->attemptNumber = 0;
		$this->jobId = 0;
		$this->syncConfig = new \airbyte\airbyte_oss\Models\Shared\AttemptSyncConfig();
	}
}
