<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SetInstancewideDestinationOauthParamsRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('destinationDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $destinationDefinitionId;
    
    /**
     * $params
     * 
     * @var array<string, mixed> $params
     */
	#[\JMS\Serializer\Annotation\SerializedName('params')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    public array $params;
    
	public function __construct()
	{
		$this->destinationDefinitionId = "";
		$this->params = [];
	}
}
