<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SetWorkflowInAttemptRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('attemptNumber')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $attemptNumber;
    
	#[\JMS\Serializer\Annotation\SerializedName('jobId')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $jobId;
    
	#[\JMS\Serializer\Annotation\SerializedName('processingTaskQueue')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $processingTaskQueue = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('workflowId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workflowId;
    
	public function __construct()
	{
		$this->attemptNumber = 0;
		$this->jobId = 0;
		$this->processingTaskQueue = null;
		$this->workflowId = "";
	}
}
