<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SlackNotificationConfiguration
{
	#[\JMS\Serializer\Annotation\SerializedName('webhook')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $webhook;
    
	public function __construct()
	{
		$this->webhook = "";
	}
}
