<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SourceDiscoverSchemaRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('connectionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $connectionId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('disable_cache')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $disableCache = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('notifySchemaChange')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $notifySchemaChange = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceId;
    
	public function __construct()
	{
		$this->connectionId = null;
		$this->disableCache = null;
		$this->notifySchemaChange = null;
		$this->sourceId = "";
	}
}
