<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum SourceDefinitionReadSourceType: string
{
    case Api = 'api';
    case File = 'file';
    case Database = 'database';
    case Custom = 'custom';
}
