<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum SourceDefinitionReadSourceTypeEnum: string
{
    case API = 'api';
    case FILE = 'file';
    case DATABASE = 'database';
    case CUSTOM = 'custom';
}
