<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * SourceCloneRequestBody - The values required to configure the source. The schema for this should have an id of the existing source along with the configuration you want to change in case.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class SourceCloneRequestBody
{
	#[\JMS\Serializer\Annotation\SerializedName('sourceCloneId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceCloneId;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceConfiguration')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SourceCloneConfiguration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SourceCloneConfiguration $sourceConfiguration = null;
    
	public function __construct()
	{
		$this->sourceCloneId = "";
		$this->sourceConfiguration = null;
	}
}
