<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * SourceRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class SourceRead
{
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     * 
     * @var mixed $connectionConfiguration
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionConfiguration')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $connectionConfiguration;
    
	#[\JMS\Serializer\Annotation\SerializedName('icon')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $icon = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceDefinitionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceDefinitionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceId;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceName;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->connectionConfiguration = null;
		$this->icon = null;
		$this->name = "";
		$this->sourceDefinitionId = "";
		$this->sourceId = "";
		$this->sourceName = "";
		$this->workspaceId = "";
	}
}
