<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * SourceDefinitionSpecification - The specification for what values are required to configure the sourceDefinition.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class SourceDefinitionSpecification
{
	public function __construct()
	{
	}
}
