<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * SourceDiscoverSchemaRead - Returns the results of a discover catalog job. If the job was not successful, the catalog field will not be present. jobInfo will aways be present and its status be used to determine if the job was successful or not.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class SourceDiscoverSchemaRead
{
	#[\JMS\Serializer\Annotation\SerializedName('breakingChange')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $breakingChange = null;
    
    /**
     * describes the available schema (catalog).
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\AirbyteCatalog $catalog
     */
	#[\JMS\Serializer\Annotation\SerializedName('catalog')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AirbyteCatalog')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AirbyteCatalog $catalog = null;
    
    /**
     * Describes the difference between two Airbyte catalogs.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\CatalogDiff $catalogDiff
     */
	#[\JMS\Serializer\Annotation\SerializedName('catalogDiff')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\CatalogDiff')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CatalogDiff $catalogDiff = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('catalogId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $catalogId = null;
    
    /**
     * Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\ConnectionStatusEnum $connectionStatus
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionStatus')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\ConnectionStatusEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ConnectionStatusEnum $connectionStatus = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('jobInfo')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SynchronousJobRead')]
    public SynchronousJobRead $jobInfo;
    
	public function __construct()
	{
		$this->breakingChange = null;
		$this->catalog = null;
		$this->catalogDiff = null;
		$this->catalogId = null;
		$this->connectionStatus = null;
		$this->jobInfo = new \airbyte\airbyte_oss\Models\Shared\SynchronousJobRead();
	}
}
