<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * SourceDiscoverSchemaWriteRequestBody - to write this requested object to database.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class SourceDiscoverSchemaWriteRequestBody
{
    /**
     * describes the available schema (catalog).
     * 
     * @var \airbyte\airbyte_oss\Models\Shared\AirbyteCatalog $catalog
     */
	#[\JMS\Serializer\Annotation\SerializedName('catalog')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\AirbyteCatalog')]
    public AirbyteCatalog $catalog;
    
	#[\JMS\Serializer\Annotation\SerializedName('configurationHash')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $configurationHash = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('connectorVersion')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $connectorVersion = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $sourceId = null;
    
	public function __construct()
	{
		$this->catalog = new \airbyte\airbyte_oss\Models\Shared\AirbyteCatalog();
		$this->configurationHash = null;
		$this->connectorVersion = null;
		$this->sourceId = null;
	}
}
