<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SourceUpdate
{
    /**
     * The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
     * 
     * @var mixed $connectionConfiguration
     */
	#[\JMS\Serializer\Annotation\SerializedName('connectionConfiguration')]
    #[\JMS\Serializer\Annotation\Type('mixed')]
    public mixed $connectionConfiguration;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('sourceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $sourceId;
    
	public function __construct()
	{
		$this->connectionConfiguration = null;
		$this->name = "";
		$this->sourceId = "";
	}
}
