<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum StreamTransformTransformType: string
{
    case AddStream = 'add_stream';
    case RemoveStream = 'remove_stream';
    case UpdateStream = 'update_stream';
}
