<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class StreamState
{
	#[\JMS\Serializer\Annotation\SerializedName('streamDescriptor')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\StreamDescriptor')]
    public StreamDescriptor $streamDescriptor;
    
    /**
     * $streamState
     * 
     * @var ?array<string, mixed> $streamState
     */
	#[\JMS\Serializer\Annotation\SerializedName('streamState')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $streamState = null;
    
	public function __construct()
	{
		$this->streamDescriptor = new \airbyte\airbyte_oss\Models\Shared\StreamDescriptor();
		$this->streamState = null;
	}
}
