<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class StreamTransform
{
	#[\JMS\Serializer\Annotation\SerializedName('streamDescriptor')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\StreamDescriptor')]
    public StreamDescriptor $streamDescriptor;
    
	#[\JMS\Serializer\Annotation\SerializedName('transformType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\StreamTransformTransformTypeEnum>')]
    public StreamTransformTransformTypeEnum $transformType;
    
    /**
     * list of field transformations. order does not matter.
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\FieldTransform> $updateStream
     */
	#[\JMS\Serializer\Annotation\SerializedName('updateStream')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\FieldTransform>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $updateStream = null;
    
	public function __construct()
	{
		$this->streamDescriptor = new \airbyte\airbyte_oss\Models\Shared\StreamDescriptor();
		$this->transformType = \airbyte\airbyte_oss\Models\Shared\StreamTransformTransformTypeEnum::ADD_STREAM;
		$this->updateStream = null;
	}
}
