<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum StreamTransformTransformTypeEnum: string
{
    case ADD_STREAM = 'add_stream';
    case REMOVE_STREAM = 'remove_stream';
    case UPDATE_STREAM = 'update_stream';
}
