<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * StreamJsonSchema - Stream schema using Json Schema specs.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class StreamJsonSchema
{
	public function __construct()
	{
	}
}
