<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class SynchronousJobRead
{
    /**
     * only present if a config id was provided.
     * 
     * @var ?string $configId
     */
	#[\JMS\Serializer\Annotation\SerializedName('configId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $configId = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('configType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobConfigType>')]
    public JobConfigType $configType;
    
	#[\JMS\Serializer\Annotation\SerializedName('connectorConfigurationUpdated')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $connectorConfigurationUpdated = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('createdAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('endedAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $endedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('logs')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\LogRead')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?LogRead $logs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('succeeded')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $succeeded;
    
	public function __construct()
	{
		$this->configId = null;
		$this->configType = \airbyte\airbyte_oss\Models\Shared\JobConfigType::CheckConnectionSource;
		$this->connectorConfigurationUpdated = null;
		$this->createdAt = 0;
		$this->endedAt = 0;
		$this->id = "";
		$this->logs = null;
		$this->succeeded = false;
	}
}
