<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


enum SyncMode: string
{
    case FullRefresh = 'full_refresh';
    case Incremental = 'incremental';
}
