<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * WebBackendConnectionListItem - Information about a connection that shows up in the connection list view.
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class WebBackendConnectionListItem
{
	#[\JMS\Serializer\Annotation\SerializedName('connectionId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $connectionId;
    
	#[\JMS\Serializer\Annotation\SerializedName('destination')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\DestinationSnippetRead')]
    public DestinationSnippetRead $destination;
    
	#[\JMS\Serializer\Annotation\SerializedName('isSyncing')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $isSyncing;
    
    /**
     * epoch time of the latest sync job. null if no sync job has taken place.
     * 
     * @var ?int $latestSyncJobCreatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('latestSyncJobCreatedAt')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $latestSyncJobCreatedAt = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('latestSyncJobStatus')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\JobStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?JobStatus $latestSyncJobStatus = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * schedule for when the the connection should run, per the schedule type
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\ConnectionScheduleData $scheduleData
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduleData')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\ConnectionScheduleData')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ConnectionScheduleData $scheduleData = null;
    
    /**
     * determine how the schedule data should be interpreted
     * 
     * @var ?\airbyte\airbyte_oss\Models\Shared\ConnectionScheduleType $scheduleType
     */
	#[\JMS\Serializer\Annotation\SerializedName('scheduleType')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\ConnectionScheduleType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ConnectionScheduleType $scheduleType = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('schemaChange')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\SchemaChange>')]
    public SchemaChange $schemaChange;
    
	#[\JMS\Serializer\Annotation\SerializedName('source')]
    #[\JMS\Serializer\Annotation\Type('airbyte\airbyte_oss\Models\Shared\SourceSnippetRead')]
    public SourceSnippetRead $source;
    
    /**
     * Active means that data is flowing through the connection. Inactive means it is not. Deprecated means the connection is off and cannot be re-activated. the schema field describes the elements of the schema that will be synced.
     * 
     * @var \airbyte\airbyte_oss\Models\Shared\ConnectionStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\ConnectionStatus>')]
    public ConnectionStatus $status;
    
	public function __construct()
	{
		$this->connectionId = "";
		$this->destination = new \airbyte\airbyte_oss\Models\Shared\DestinationSnippetRead();
		$this->isSyncing = false;
		$this->latestSyncJobCreatedAt = null;
		$this->latestSyncJobStatus = null;
		$this->name = "";
		$this->scheduleData = null;
		$this->scheduleType = null;
		$this->schemaChange = \airbyte\airbyte_oss\Models\Shared\SchemaChange::NO_CHANGE;
		$this->source = new \airbyte\airbyte_oss\Models\Shared\SourceSnippetRead();
		$this->status = \airbyte\airbyte_oss\Models\Shared\ConnectionStatus::ACTIVE;
	}
}
