<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class WebhookConfigWrite
{
    /**
     * an auth token, to be passed as the value for an HTTP Authorization header.
     * 
     * @var ?string $authToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('authToken')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $authToken = null;
    
    /**
     * human readable name for this webhook e.g. for UI display.
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * if supplied, the webhook config will be validated by checking that this URL returns a 2xx response.
     * 
     * @var ?string $validationUrl
     */
	#[\JMS\Serializer\Annotation\SerializedName('validationUrl')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $validationUrl = null;
    
	public function __construct()
	{
		$this->authToken = null;
		$this->name = null;
		$this->validationUrl = null;
	}
}
