<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


class WorkflowStateRead
{
	#[\JMS\Serializer\Annotation\SerializedName('running')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $running;
    
	public function __construct()
	{
		$this->running = false;
	}
}
