<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * WorkspaceRead - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class WorkspaceRead
{
	#[\JMS\Serializer\Annotation\SerializedName('anonymousDataCollection')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $anonymousDataCollection = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('customerId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $customerId;
    
	#[\JMS\Serializer\Annotation\SerializedName('defaultGeography')]
    #[\JMS\Serializer\Annotation\Type('enum<airbyte\airbyte_oss\Models\Shared\GeographyEnum>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GeographyEnum $defaultGeography = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('displaySetupWizard')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $displaySetupWizard = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $email = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('feedbackDone')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $feedbackDone = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('firstCompletedSync')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $firstCompletedSync = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('initialSetupComplete')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $initialSetupComplete;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('news')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $news = null;
    
    /**
     * $notifications
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\Notification> $notifications
     */
	#[\JMS\Serializer\Annotation\SerializedName('notifications')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\Notification>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $notifications = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('securityUpdates')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $securityUpdates = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
    /**
     * $webhookConfigs
     * 
     * @var ?array<\airbyte\airbyte_oss\Models\Shared\WebhookConfigRead> $webhookConfigs
     */
	#[\JMS\Serializer\Annotation\SerializedName('webhookConfigs')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\WebhookConfigRead>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $webhookConfigs = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('workspaceId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workspaceId;
    
	public function __construct()
	{
		$this->anonymousDataCollection = null;
		$this->customerId = "";
		$this->defaultGeography = null;
		$this->displaySetupWizard = null;
		$this->email = null;
		$this->feedbackDone = null;
		$this->firstCompletedSync = null;
		$this->initialSetupComplete = false;
		$this->name = "";
		$this->news = null;
		$this->notifications = null;
		$this->securityUpdates = null;
		$this->slug = "";
		$this->webhookConfigs = null;
		$this->workspaceId = "";
	}
}
