<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace airbyte\airbyte_oss\Models\Shared;


/**
 * WorkspaceReadList - Successful operation
 * 
 * @package airbyte\airbyte_oss\Models\Shared
 * @access public
 */
class WorkspaceReadList
{
    /**
     * $workspaces
     * 
     * @var array<\airbyte\airbyte_oss\Models\Shared\WorkspaceRead> $workspaces
     */
	#[\JMS\Serializer\Annotation\SerializedName('workspaces')]
    #[\JMS\Serializer\Annotation\Type('array<airbyte\airbyte_oss\Models\Shared\WorkspaceRead>')]
    public array $workspaces;
    
	public function __construct()
	{
		$this->workspaces = [];
	}
}
